# Generated by Django 3.2.4 on 2021-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.PositiveSmallIntegerField(choices=[(1, 'Select below'), (2, 'Tsunami'), (3, 'Cyclone')], default=1)),
                ('is_solved', models.BooleanField()),
            ],
        ),
    ]
