# Generated by Django 3.2.4 on 2021-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='disaster_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Select below'), (2, 'Tsunami'), (3, 'Cyclone'), (4, 'Flood'), (5, 'Eathequake'), (6, 'War'), (7, 'Pandemic')], default=1),
        ),
    ]
