# Generated by Django 3.2.4 on 2021-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crises', '0003_alter_resource_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Helper', 'Helper'), ('Teacher', 'Teacher'), ('Rescuer', 'Rescuer'), ('Medical', 'Medical'), ('Nutrition', 'Nutrition'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Transport', 'Transport')], max_length=20, unique=True),
        ),
    ]
