@help_seeker_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjIsImV4cCI6MTYyNDgwMDAzMiwidHlwZSI6IkhlbHAtc2Vla2VyIn0.Y8ueQ-cEMJH2lU9PHpb02UTJVUZEnrLeEuwHd2yEABM
@NGO_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImV4cCI6MTYyNDc5NTM4NywidHlwZSI6Ik5HTyJ9.HGkeSFedlq10E-4cxxZCx8Lve_rb-6lmAf729Ed6484
@HSuserId = 2
@NGOuserId = 3

### GET all crises
GET http://localhost:8000/api/crises/

### GET single crisis
GET http://localhost:8000/api/crises/crisis/1/

### Edit/Update a crisis
PUT http://localhost:8000/api/crises/crisis/1/
Content-Type: application/json
Authorization: Bearer {{help_seeker_token}}

{
  "disasterType": "Flood",
  "isSolved": false
}

### Delete a single crisis
DELETE http://localhost:8000/api/crises/crisis/2/
Content-Type: application/json
Authorization: Bearer {{help_seeker_token}}

### Create a crisis
POST http://localhost:8000/api/crises/
Content-Type: application/json
Authorization: Bearer {{help_seeker_token}}

{
  "disasterType": "Tsunami",
  "isSolved": false,
  "latitude": 53.6458,
  "longitude": 1.7850,
  "placeName": "Huddersfield",
  "country": "United Kingdom",
  "disasterDescription": "pretty big flood, no casualties",
  "placeType": "country",
  "requests": [
    {
    "resource": 1,
    "quantity": 5
    },
    {
    "resource": 2,
    "quantity": 5
    },
    {
    "resource": 3,
    "quantity": 5
    },
        {
    "resource": 4,
    "quantity": 5
    },
    {
    "resource": 5,
    "quantity": 5
    },
    {
    "resource": 6,
    "quantity": 5
    },
    {
    "resource": 7,
    "quantity": 5
    },
    {
    "resource": 8,
    "quantity": 5
    },
    {
    "resource": 9,
    "quantity": 5
    },
    {
    "resource": 10,
    "quantity": 5
    }
  ]
}

### Edit/Update a Request
PUT http://localhost:8000/api/crises/13/
Content-Type: application/json
Authorization: Bearer {{help_seeker_token}}

{
  "resource": true,
  "quantity": 1000,
}

### Create a user HELP-SEEKER
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "userType": "Help-seeker",
  "username": "hs3",
  "email": "hs3@worco.com",
  "password": "Pass1234+=",
  "passwordConfirmation": "Pass1234+=",
  "profilePictureUrl": "fake url",
  "country": "France"
}

### Create a user HELP-SEEKER 2
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "userType": "Help-seeker",
  "username": "",
  "email": "hs4@worco.com",
  "password": "Pass1234+=",
  "passwordConfirmation": "Pass1234+=",
  "profilePictureUrl": "fake url",
  "country": "UK"
}

### Create a user NGO 1
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "userType": "NGO",
  "username": "ngo1",
  "email": "ngo1@worco.com",
  "password": "Pass1234+=",
  "passwordConfirmation": "Pass1234+=",
  "profilePictureUrl": "fake url"
}

### Create a user NGO 2
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "userType": "NGO",
  "username": "ngo2",
  "email": "ngo2@worco.com",
  "password": "Pass1234+=",
  "passwordConfirmation": "Pass1234+=",
  "profilePictureUrl": "fake url"
}

### Login user Help Seeker 1
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "hs1@worco.com",
  "password": "Pass1234+="
}

### Login user NGO 1
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "ngo1@worco.com",
  "password": "Pass1234+="
}

### Login user NGO 2
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "ngo2@worco.com",
  "password": "Pass1234+="
}

### View user profile
GET http://localhost:8000/api/auth/profile/2/

### Get disaster types
GET http://localhost:8000/api/crises/types/
Content-Type: application/json

### Get resource name + type
GET http://localhost:8000/api/crises/resources/
Content-Type: application/json

### Get NGO resources
GET http://localhost:8000/api/crises/ngo_resources/
Content-Type: application/json
Authorization: Bearer {{NGO_token}}

### Create NGO Resources
POST http://localhost:8000/api/crises/ngo_resources/
Content-Type: application/json
Authorization: Bearer {{NGO_token}}

{
  "resources": [
    {
    "resource": 1,
    "quantity": 200
    },
    {
    "resource": 2,
    "quantity": 200
    },
    {
    "resource": 3,
    "quantity": 200
    },
        {
    "resource": 4,
    "quantity": 200
    },
    {
    "resource": 5,
    "quantity": 200
    },
    {
    "resource": 6,
    "quantity": 200
    },
    {
    "resource": 7,
    "quantity": 200
    },
    {
    "resource": 8,
    "quantity": 200
    },
    {
    "resource": 9,
    "quantity": 200
    },
    {
    "resource": 10,
    "quantity": 200
    }
  ]
}

### Edit/Update NGO Resources
PUT http://localhost:8000/api/crises/ngo_resources/1/
Content-Type: application/json
Authorization: Bearer {{NGO_token}}

{
  "resource": 1,
  "quantity": 123
}

### Create a crisis (for errors)
POST http://localhost:8000/api/crises/
Content-Type: application/json
Authorization: Bearer {{help_seeker_token}}

{
  "disasterType": "",
  "isSolved": false,
  "longitude": "",
  "latitude": "",
  "placeName": "",
  "country": "",
  "disasterDescription": "",
  "requests": [
    {
    "resource": 1,
    "quantity": ""
    },
    {
    "resource": 2,
    "quantity": ""
    },
    {
    "resource": 3,
    "quantity": ""
    },
        {
    "resource": 4,
    "quantity": ""
    },
    {
    "resource": 5,
    "quantity": ""
    },
    {
    "resource": 6,
    "quantity": ""
    },
    {
    "resource": 7,
    "quantity": ""
    },
    {
    "resource": 8,
    "quantity": ""
    },
    {
    "resource": 9,
    "quantity": ""
    },
    {
    "resource": 10,
    "quantity": ""
    }
  ]
}

### Get Specific HS user crisis list
GET http://localhost:8000/api/crises/{{HSuserId}}/
Content-Type: application/json
Authorization: Bearer {{help_seeker_token}}